---
title: FOREVR
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: thebandforevr@gmail.com
description: 'Official repository of online resources relating to the business and
  marketing of the brand FOREVR, based in Brisbane, Australia

'
baseurl: ''
url: http://thebandforevr.com
twitter_username: thebandforevr
github_username: mthrflwr
markdown: kramdown
